In [59]:
# Import analysis libraries.
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [60]:
# Create path variable for re-use when importing data.
path = r'C:\Users\sorca\Documents\Achievement_6\6_1'

In [61]:
path

'C:\\Users\\sorca\\Documents\\Achievement_6\\6_1'

In [62]:
df_all_years = pd.read_csv(('2015-2019.csv'), index_col = False)

In [63]:
df_all_years.head()

,Happiness Rank,Country,Region,Happiness Score,GDP per Capita,Social support,Life Expectancy,Freedom,Perceptions of corruption,Generosity,Year
0,1,Switzerland,Western Europe,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,2,Iceland,Western Europe,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,3,Denmark,Western Europe,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,4,Norway,Western Europe,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,5,Canada,North America,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

In [64]:
summary = df_all_years.describe()

In [65]:
summary.head()

,Happiness Rank,Happiness Score,GDP per Capita,Social support,Life Expectancy,Freedom,Perceptions of corruption,Generosity,Year
count,781.000000,781.000000,781.000000,781.000000,781.000000,781.000000,781.000000,781.000000,781.000000
mean,78.701665,5.378940,0.917773,1.079861,0.613763,0.411611,0.125511,0.218507,2016.994878
std,45.211235,1.128177,0.405114,0.327298,0.246225,0.151354,0.105732,0.122384,1.417826
min,1.000000,2.693000,0.015300,0.000000,0.005565,0.005890,0.001000,0.000000,2015.000000
25%,40.000000,4.509000,0.611000,0.870210,0.440550,0.309530,0.054000,0.130000,2016.000000

In [73]:
summary.to_csv('summary_statistics.csv')